language: python
python:
  - "2.7"
  - "3.6"

env:
  global:
      - PYTHONPATH=.

install:
  - "pip install --verbose -r requirements.txt"
  - "pip install --verbose -r tests/requirements.txt"

# command to run tests
script:
  - "python -m unittest discover tests"

